all:	shapedemo hellovg randcircle raspi colortab

shapedemo:	shapedemo.go
		go build shapedemo.go

hellovg:	hellovg.go
		go build hellovg.go

randcircle:	randcircle.go
		go build randcircle.go

raspi:	raspi.go
		go build raspi.go

colortab:	colortab.go
		go build colortab.go

test:	shapedemo
		./shapedemo demo 5
